version: '3.6'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pslq-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  pslq-data: