version: '3.6'

services:
  web:
    build:
      context: .
      cache_from:
        - tomcat:latest
    image: hvits3rk/tomcat-no-root:latest
    ports:
      - 8080:8080
    volumes:
      - ./deploy/lesson5-0.1.war:/usr/local/tomcat/webapps/ROOT.war